### ISSUE TITLE
Setup postgres persistent volume in docker-compose correctly

### ISSUE THREAD

**Issue by radoslavzeman** [bratislava/bratislava.sk#1378]
Should be like this (see the last line), and also `postgres` folder needs to be in gitignore.

```
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: strapi
      PGPORT: 5432
    expose:
      - '5432'
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
```
